### ISSUE TITLE
The goal pose passed to this planner must be in the map frame.  It is instead in the /map frame.

### ISSUE THREAD

**Issue by Ghofrane101** [WPI-RAIL/nav2djs#46]
Hello , 

So i am trying to use Nav2djs to send my project's robot to different locations in my 2d map using this example : http://wiki.ros.org/nav2djs/Tutorials/CreatingABasicNav2DWidget . 

So far , i am able to see the robot on the map and i can send it to different goals using rviz. My problem is every time i double click in the 2d map to specify a goal to the robot in the map, i get errors in one of my launch files ( the one that launches the move_base) and the robot doesn't move. 

[ERROR] [1617013162.716205551, 2844.706000000]: The goal pose passed to this planner must be in the map frame.  It is instead in the /map frame.
[ INFO] [1617013162.716235264, 2844.706000000]: Nearest node index: 0

[ INFO] [1617013162.716256593, 2844.706000000]: Nearest node index: 0

[ERROR] [1617013162.716277433, 2844.706000000]: The goal pose passed to this planner must be in the map frame.  It is instead in the /map frame.
[ INFO] [1617013162.716303435, 2844.706000000]: Nearest node index: 0

[ INFO] [1617013162.716324705, 2844.706000000]: Nearest node index: 0
.... 

I have been looking everywhere for a while now and i can't seem to find a solution.. Has anyone encountered this before ? am i missing something ? 

I am working on ros melodic on Ubuntu 18.04. 
Thank you !

**Comment by phurkornt** [comment]
how did you solved this problem?
